### ISSUE TITLE
window.exports未配置

### ISSUE THREAD

**Issue by chkinglee** [RipperTs/2fa-read-message-code#1]
utools v4.0.1 使用2fa提示 window.exports未配置

**Comment by RipperTs** [comment]
大概率是因为inter版本的MacOS问题，你可以到 https://github.com/RipperTs/2fa-read-message-code/releases
下载对应芯片版本的`upx`包，然后呼出 `uTools`，粘贴到`uTools`的搜索框内安装。

**Comment by chkinglee** [comment]
插件运行出错,请将以下错误信息发送给作者处理:

Error: Cannot find module '/Users/chkinglee/Library/Application Support/uTools/plugins/unsafe-4b01096355fa72e4bcfd61aebab831a7.asar/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-x64/node_sqlite3.node'
Require stack:
- /Users/chkinglee/Library/Application Support/uTools/plugins/unsafe-4b01096355fa72e4bcfd61aebab831a7.asar/node_modules/sqlite3/lib/sqlite3-binding.js
- /Users/chkinglee/Library/Application Support/uTools/plugins/unsafe-4b01096355fa72e4bcfd61aebab831a7.asar/node_modules/sqlite3/lib/sqlite3.js
- /Users/chkinglee/Library/Application Support/uTools/plugins/unsafe-4b01096355fa72e4bcfd61aebab831a7.asar/preload.js

**Comment by RipperTs** [comment]
你那边是m1芯片的MacOS吗？

**Comment by chkinglee** [comment]
嗯是的，我刚刚也是直接下载安装的m芯片的包

**Comment by RipperTs** [comment]
看起来还是编译的问题了，我这边试试使用其他方式实现吧。

**Comment by RipperTs** [comment]
可以加下我wx: ripperts 我发你新的upx测试下看看

**Comment by RipperTs** [comment]
新的upx已发布，改用了Python实现，应该会解决这个问题了。
如果还有问题，可重新打开此 `issues`
